version: '3'

services:
  api:
    build: .
    volumes:
      - .:/app
    expose:
      - '${PORT}'
    ports:
      - '${PORT}:${PORT}'
    command: npm start
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5431:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: